---
- name: Install Github Runner and tools
  hosts: github-runner
  become: yes
  vars:
    - github_account: <account-name>
    - github_repo: <repo-name>
  # - runner_org: true # If runner is org wide
  roles:
    - monolithprojects.github_actions_runner
    - install_tools