name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ansible/ansible-lint-action@master
      with:
        targets: |
          play.yml
          roles/install_tools
        args: "-x 301"
